spring:
  redis:
    uri: redis://xxxxxxxxx
  mail:
    host: smtp.gmail.com
    port: 587
    username: saptarshi.dev.test@gmail.com
    password: xxxx xxxx xxxx xxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
